### ISSUE TITLE
SWAPI analogue

### ISSUE THREAD

**Issue by Letivan** [tbone849/star-wars-guide#9]
Hey. Here is a link to the full swapi analogue.
http://starwars.andgein.ru/

**Comment by tbone849** [comment]
Will check it out thanks!

**Comment by Juriy** [comment]
https://swapi.dev - another service to consider (running AWS, i'm planning to maintain it, since some of my educational materials depend on it)

**Comment by tbone849** [comment]
Thanks all! Back in business!

**Comment by tbone849** [comment]
@Juriy your API appears to be down.
